enabled: true

service:
  enabled: true
  type: ClusterIP
  port: 8429

ingress:
  enabled: false
  className: nginx
  annotations: {}
  tls: []

replicaCount: 1

remoteWriteUrl: "" # when empty, built from global protocol/ports/paths

scrapeInterval: 30s
scrapeTargets: [] # optional override; when empty, use global defaults

resources: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

