apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}-service-b
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: service-b
      {{- include "demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service-b
        {{- include "demo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with (.Values.imagePullSecrets | default (.Values.global).imagePullSecrets) }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: service-b
          image: "{{ include "demo.imageRepository" (dict "repository" .Values.image.repository "Values" .Values) }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
          {{- with .Values.serviceB.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.serviceB.port }}
          env:
            {{- range $key, $value := .Values.serviceB.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
