service:
  type: ClusterIP
  port: 9410
  extraPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts: []
  tls: []

persistence:
  enabled: true
  existingClaim: "" # use existing PVC name instead of creating one
  storageClassName: "" # leave empty to use default
  accessModes: ["ReadWriteOnce"]
  size: 10Gi
  mountPath: /vtraces

args:
  - "-storageDataPath=/vtraces"
  - "-httpListenAddr=:9410"
  - "-otlpGRPCListenAddr=:4317"
  - "-otlpGRPC.tls=false"
httpPathPrefix: ""
healthPath: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
