image:
  repository: limitium/victoria-load
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceA:
  name: service-a
  port: 8000
  targetServiceName: service-b
  env:
    SERVICE_NAME: service-a
    OTEL_EXPORTER_OTLP_ENDPOINT: http://victoria-traces:4317
  resources:
    requests:
      cpu: "0.25"
      memory: 1Gi
    limits:
      memory: 1Gi

serviceB:
  name: service-b
  port: 8000
  env:
    SERVICE_NAME: service-b
    OTEL_EXPORTER_OTLP_ENDPOINT: http://victoria-traces:4317
  resources:
    requests:
      cpu: "0.25"
      memory: 1Gi
    limits:
      memory: 1Gi

loadGenerator:
  enabled: true
  image:
    repository: curlimages/curl
    tag: latest
    pullPolicy: IfNotPresent
  command: []
  resources:
    requests:
      cpu: "0.25"
      memory: 1Gi
    limits:
      memory: 1Gi
