{{- if and .Values.enabled .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmagent.fullname" . }}
  labels:
    {{- include "vmagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vmagent.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      {{- $port := default "" .Values.global.ports.vmagent }}
      port: {{ default .Values.service.port $port }}
      targetPort: http
{{- end }}

