service:
  type: ClusterIP
  port: 8428

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts: []
  tls: []

persistence:
  enabled: true
  existingClaim: "" # use existing PVC name instead of creating one
  storageClass: "" # leave empty to use default
  accessModes: ["ReadWriteOnce"]
  size: 10Gi
  mountPath: /vmdata

args:
  - "-storageDataPath=/vmdata"
  - "-httpListenAddr=:8428"
httpPathPrefix: ""
healthPath: ""
resources: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
