
apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      {{- $port := default "" .Values.global.ports.grafana }}
      port: {{ default .Values.service.port $port }}
      targetPort: http
